DROP USER ERS CASCADE;
CREATE USER ERS
    IDENTIFIED BY p4ssw0rd
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA 10M ON USERS;
    
GRANT CONNECT TO ERS;
GRANT RESOURCE TO ERS;
GRANT CREATE SESSION TO ERS;
GRANT CREATE TABLE TO ERS;
GRANT CREATE VIEW TO ERS;