/*
    Seeding the initial test data into the database
*/

INSERT INTO STATUS VALUES (STATUS_SEQ.NEXTVAL, 'new');
INSERT INTO STATUS VALUES (STATUS_SEQ.NEXTVAL, 'approve');
INSERT INTO STATUS VALUES (STATUS_SEQ.NEXTVAL, 'deny');

INSERT INTO EMPLOYEE (ID, USERNAME, PASSWORD, EMAIL, FNAME, LNAME) VALUES (EMPLOYEE_SEQ.NEXTVAL, 'rmarinoff', 'pass', 'ryan.marinoff@gmail.com', 'Ryan', 'Marinoff');
INSERT INTO EMPLOYEE VALUES (EMPLOYEE_SEQ.NEXTVAL, 'tbradford', 'pass', 'doctortye1987@gmail.com', 'Tye', 'Bradford',
    (SELECT ID FROM EMPLOYEE WHERE USERNAME='rmarinoff'));
SELECT * FROM EMPLOYEE;
select * from employee where manager_id is null;
    
INSERT INTO REIMBURSEMENT VALUES (REIMBURSEMENT_SEQ.NEXTVAL, 2000.00, 
    (SELECT ID FROM EMPLOYEE WHERE USERNAME='tbradford'));

INSERT INTO STATUS_LOG VALUES (STATUS_LOG_SEQ.NEXTVAL, 
    (SELECT ID FROM STATUS WHERE CODE='new'),
    (SELECT ID FROM REIMBURSEMENT WHERE EMPLOYEE_ID=
        (SELECT ID FROM EMPLOYEE WHERE USERNAME='tbradford')),
    (SELECT CURRENT_DATE FROM DUAL));
    
COMMIT;
    